import { Fira_Sans_Condensed } from "next/font/google";
import "./globals.css";

const firaSansCondensed = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-fira-sans-condensed",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${firaSansCondensed.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
